// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiculeLocation.Backend.Data;

#nullable disable

namespace VehiculeLocation.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112143011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateEnd = new DateTime(2025, 12, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculeId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateEnd = new DateTime(2025, 12, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculeId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateEnd = new DateTime(2025, 12, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculeId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateEnd = new DateTime(2025, 12, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculeId = 1
                        });
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomaticTransmission")
                        .HasColumnType("INTEGER");

                    b.Property<float>("DailyLocationPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Motorisation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Place")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutomaticTransmission = false,
                            DailyLocationPrice = 30.5f,
                            ImagePath = "https://lh6.googleusercontent.com/proxy/HEmJ7BvDYuo0uaBAecqWSianL5MBS7XzuqV7Nu-scTwvXRipC-hl4cd9crmQyWRGlpVFfhzCUNeDJr5najGvzJgFieuCF71nqwFxy22zmJpFOaGjHaieImL9dQCHvliO5n5Z8AgF83m7qs4ntaPlLsE",
                            Modele = "Renault Clio V",
                            Motorisation = "Essence",
                            Place = 5
                        },
                        new
                        {
                            Id = 2,
                            AutomaticTransmission = true,
                            DailyLocationPrice = 65f,
                            ImagePath = "https://lh6.googleusercontent.com/proxy/HEmJ7BvDYuo0uaBAecqWSianL5MBS7XzuqV7Nu-scTwvXRipC-hl4cd9crmQyWRGlpVFfhzCUNeDJr5najGvzJgFieuCF71nqwFxy22zmJpFOaGjHaieImL9dQCHvliO5n5Z8AgF83m7qs4ntaPlLsE",
                            Modele = "Peugeot 3008",
                            Motorisation = "Diesel",
                            Place = 5
                        },
                        new
                        {
                            Id = 3,
                            AutomaticTransmission = true,
                            DailyLocationPrice = 25f,
                            ImagePath = "https://lh6.googleusercontent.com/proxy/HEmJ7BvDYuo0uaBAecqWSianL5MBS7XzuqV7Nu-scTwvXRipC-hl4cd9crmQyWRGlpVFfhzCUNeDJr5najGvzJgFieuCF71nqwFxy22zmJpFOaGjHaieImL9dQCHvliO5n5Z8AgF83m7qs4ntaPlLsE",
                            Modele = "Renault Twingo",
                            Motorisation = "Electrique",
                            Place = 5
                        },
                        new
                        {
                            Id = 4,
                            AutomaticTransmission = false,
                            DailyLocationPrice = 35f,
                            ImagePath = "https://lh6.googleusercontent.com/proxy/HEmJ7BvDYuo0uaBAecqWSianL5MBS7XzuqV7Nu-scTwvXRipC-hl4cd9crmQyWRGlpVFfhzCUNeDJr5najGvzJgFieuCF71nqwFxy22zmJpFOaGjHaieImL9dQCHvliO5n5Z8AgF83m7qs4ntaPlLsE",
                            Modele = "Citroën C3",
                            Motorisation = "Essence",
                            Place = 5
                        });
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Location", b =>
                {
                    b.HasOne("VehiculeLocation.Backend.Models.Vehicule", "Vehicule")
                        .WithMany("Locations")
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Vehicule", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
