// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiculeLocation.Backend.Data;

#nullable disable

namespace VehiculeLocation.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251014095426_SeedVehicules")]
    partial class SeedVehicules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modele")
                        .HasColumnType("TEXT");

                    b.Property<int>("Place")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Modele = "Renault Clio V",
                            Place = 5
                        },
                        new
                        {
                            Id = 2,
                            Modele = "Peugeot 3008",
                            Place = 5
                        },
                        new
                        {
                            Id = 3,
                            Modele = "Renault Twingo",
                            Place = 5
                        },
                        new
                        {
                            Id = 4,
                            Modele = "Citroën C3",
                            Place = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
