// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiculeLocation.Backend.Data;

#nullable disable

namespace VehiculeLocation.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106152835_AjoutVehicleImagePath")]
    partial class AjoutVehicleImagePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomaticTransmission")
                        .HasColumnType("INTEGER");

                    b.Property<float>("DailyLocationPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Motorisation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Place")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutomaticTransmission = false,
                            DailyLocationPrice = 30.5f,
                            ImagePath = "https://lh6.googleusercontent.com/proxy/HEmJ7BvDYuo0uaBAecqWSianL5MBS7XzuqV7Nu-scTwvXRipC-hl4cd9crmQyWRGlpVFfhzCUNeDJr5najGvzJgFieuCF71nqwFxy22zmJpFOaGjHaieImL9dQCHvliO5n5Z8AgF83m7qs4ntaPlLsE",
                            Modele = "Renault Clio V",
                            Motorisation = "Essence",
                            Place = 5
                        },
                        new
                        {
                            Id = 2,
                            AutomaticTransmission = true,
                            DailyLocationPrice = 65f,
                            ImagePath = "https://lh6.googleusercontent.com/proxy/HEmJ7BvDYuo0uaBAecqWSianL5MBS7XzuqV7Nu-scTwvXRipC-hl4cd9crmQyWRGlpVFfhzCUNeDJr5najGvzJgFieuCF71nqwFxy22zmJpFOaGjHaieImL9dQCHvliO5n5Z8AgF83m7qs4ntaPlLsE",
                            Modele = "Peugeot 3008",
                            Motorisation = "Diesel",
                            Place = 5
                        },
                        new
                        {
                            Id = 3,
                            AutomaticTransmission = true,
                            DailyLocationPrice = 25f,
                            ImagePath = "https://lh6.googleusercontent.com/proxy/HEmJ7BvDYuo0uaBAecqWSianL5MBS7XzuqV7Nu-scTwvXRipC-hl4cd9crmQyWRGlpVFfhzCUNeDJr5najGvzJgFieuCF71nqwFxy22zmJpFOaGjHaieImL9dQCHvliO5n5Z8AgF83m7qs4ntaPlLsE",
                            Modele = "Renault Twingo",
                            Motorisation = "Electrique",
                            Place = 5
                        },
                        new
                        {
                            Id = 4,
                            AutomaticTransmission = false,
                            DailyLocationPrice = 35f,
                            ImagePath = "https://lh6.googleusercontent.com/proxy/HEmJ7BvDYuo0uaBAecqWSianL5MBS7XzuqV7Nu-scTwvXRipC-hl4cd9crmQyWRGlpVFfhzCUNeDJr5najGvzJgFieuCF71nqwFxy22zmJpFOaGjHaieImL9dQCHvliO5n5Z8AgF83m7qs4ntaPlLsE",
                            Modele = "Citroën C3",
                            Motorisation = "Essence",
                            Place = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
