// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiculeLocation.Backend.Data;

#nullable disable

namespace VehiculeLocation.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112152442_RenameOfTheMotorisationEnum")]
    partial class RenameOfTheMotorisationEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateEnd = new DateTime(2025, 12, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculeId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateEnd = new DateTime(2025, 12, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculeId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateEnd = new DateTime(2025, 12, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculeId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateEnd = new DateTime(2025, 12, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            VehiculeId = 1
                        });
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<float>("DailyRentalPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutomaticTransmission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Motorisation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Renault",
                            DailyRentalPrice = 30.5f,
                            Description = "Une voiture qui roule",
                            ImagePath = "https://upload.wikimedia.org/wikipedia/commons/6/6d/Dunkerque-1.jpg",
                            IsAutomaticTransmission = false,
                            Model = "Clio V",
                            Motorisation = "Petrol",
                            Seats = 5
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Peugeot",
                            DailyRentalPrice = 65f,
                            Description = "Une voiture qui roule",
                            ImagePath = "https://upload.wikimedia.org/wikipedia/commons/6/6d/Dunkerque-1.jpg",
                            IsAutomaticTransmission = true,
                            Model = "3008",
                            Motorisation = "Diesel",
                            Seats = 5
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Renault",
                            DailyRentalPrice = 25f,
                            Description = "Une voiture qui roule",
                            ImagePath = "https://upload.wikimedia.org/wikipedia/commons/6/6d/Dunkerque-1.jpg",
                            IsAutomaticTransmission = true,
                            Model = "Twingo",
                            Motorisation = "Electric",
                            Seats = 5
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Citroën",
                            DailyRentalPrice = 35f,
                            Description = "Une voiture qui roule",
                            ImagePath = "https://upload.wikimedia.org/wikipedia/commons/6/6d/Dunkerque-1.jpg",
                            IsAutomaticTransmission = false,
                            Model = "C3",
                            Motorisation = "Petrol",
                            Seats = 5
                        });
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Rental", b =>
                {
                    b.HasOne("VehiculeLocation.Backend.Models.Vehicle", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Vehicle", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
